local prompt = require("review_explain.prompt")

describe("review_explain.prompt", function()
  it("embeds the file path, language, and code in the user message", function()
    local msg = prompt.build_user_message("local x = 1", "/tmp/foo.lua", "lua")
    assert.truthy(msg:find("/tmp/foo.lua", 1, true))
    assert.truthy(msg:find("lua", 1, true))
    assert.truthy(msg:find("local x = 1", 1, true))
  end)

  it("exposes a non-empty system prompt that demands fenced JSON output", function()
    assert.is_string(prompt.SYSTEM_PROMPT)
    assert.truthy(prompt.SYSTEM_PROMPT:find("JSON", 1, true))
    assert.truthy(prompt.SYSTEM_PROMPT:find("start_line", 1, true))
  end)
end)
